# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default
  #vmImage: ubuntu-latest

steps:
- checkout: self

- script:  ls
  
  displayName: 'Run a one-line script'

- script: | 
    cd aks-terraform 
    ls
- script: ls
- script: |
    cd aks-terraform
    terraform init
  displayName: init

 
- script: |
    cd aks-terraform
    terraform plan
  displayName: plan
 

- script: |
    cd aks-terraform
    terraform apply -auto-approve
  displayName: apply


- script: |
    cd aks-terraform
    terraform destroy -auto-approve
  displayName: destroy